# Site settings

author: Bobliu
email: -@email.com
twitter_username: archer-fedora
github_username:  archer-fedora
googleplus_username: archer-fedora

head-title: Bobliu's blog
title: 路漫求索正当时，半城绿树半城花

baseurl: /blog    # the subpath of your site, "/blog"
url: ""


# footer 
description: "Do what you want, Study what you need, \nLove the person who you love. Only Keep On"

favo: "路漫漫其修远兮 吾将上下而求索"
descrpt: "“巧者劳而智者忧，无能者无所求，饱食而遨游，泛若不系之舟”  ——《南华经》\n "


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 5
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

